import React,{useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import i18n from '../i18n';
import {getStorageStatus} from './storage';

const english={mp_back:'Back to activities',mp_help:'How to play',mp_help_text:'Fill each row, column and 3×3 box with 1–9 once. Select a cell, then use the number pad. Notes record candidates. The given numbers are locked. You can pause, undo, redo or request a hint.',mp_saved:'Automatically saved in this browser',mp_unsaved:'Browser storage is unavailable. Progress is kept on this page only.',mp_bank:'3014 puzzles · five difficulty levels',mp_fill:'Fill',mp_notes:'Notes',mp_redo:'Redo',mp_mode:'Input mode',mp_dark:'Dark theme',mp_select:'Select an empty cell, then choose a number.',mp_locked:'This number belongs to the original puzzle.',mp_selected:'Row {{row}} · column {{column}}',mp_save:'Save puzzle',mp_saving:'Saving…',mp_checking:'Checking for a unique solution…',mp_no_solution:'This puzzle has no solution.',mp_multiple:'This puzzle has several solutions. Add more given numbers.',mp_check_error:'Could not check the puzzle. Please try again.'};
const chinese={mp_back:'返回活动',mp_help:'怎么玩',mp_help_text:'每行、每列和每个3×3宫各填一次1–9。先选格，再点数字盘；笔记用来记录候选数字。原题数字不能改，可暂停、撤销、重做或查看提示。',mp_saved:'进度自动保存在此浏览器',mp_unsaved:'浏览器存档不可用，当前进度仅保留在此页。',mp_bank:'3014道题 · 五档难度',mp_fill:'填写',mp_notes:'笔记',mp_redo:'重做',mp_mode:'输入模式',mp_dark:'深色主题',mp_select:'先选空格，再点数字盘。',mp_locked:'这是原题数字，不能修改。',mp_selected:'第{{row}}行 · 第{{column}}列',mp_save:'保存数独',mp_saving:'正在保存…',mp_checking:'正在检查唯一解…',mp_no_solution:'这道题没有解，请检查原题数字。',mp_multiple:'这道题有多个解，请再补充原题数字。',mp_check_error:'暂时无法检查题目，请重试。'};
for(const language of ['en','fr','es','de','it','pt','zh'])i18n.addResourceBundle(language,'translation',language==='zh'?chinese:english,true,false);

export function ClassroomShell({children}:{children:React.ReactNode}){
 const {t,i18n}=useTranslation();const [saved,setSaved]=useState(getStorageStatus()),help=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'&&help.current?.open){event.preventDefault();event.stopImmediatePropagation();help.current.close();}};window.addEventListener('keydown',escape,true);return()=>window.removeEventListener('keydown',escape,true);},[]);
 useEffect(()=>{document.documentElement.lang=i18n.language;},[i18n.language]);
 useEffect(()=>{const status=()=>setSaved(getStorageStatus());window.addEventListener('mp-sudoku-storage',status);const frame=requestAnimationFrame(()=>{(window as any).__mpReady=true;if(parent!==window&&location.origin!=='null')parent.postMessage({type:'mp-ready',id:'sudoku'},location.origin);});return()=>{cancelAnimationFrame(frame);window.removeEventListener('mp-sudoku-storage',status);};},[]);
 const back=()=>{if(parent!==window&&location.origin!=='null')parent.postMessage({type:'mp-close',id:'sudoku'},location.origin);else location.href='../../index.html#library';};
 return <><div className="sudoku-island-bar"><button onClick={back}>{'← '+t('mp_back')}</button><span>{t('mp_bank')}</span><button className="mp-help-trigger" onClick={()=>help.current?.showModal()}>{i18n.language==='zh'?'提示':t('mp_help')}</button><p className="sudoku-save-status" role="status" data-saved={saved}>{t(saved?'mp_saved':'mp_unsaved')}</p></div><dialog ref={help} className="mp-help-dialog" aria-label={t('mp_help')} onClick={event=>{const r=event.currentTarget.getBoundingClientRect();if(event.target===event.currentTarget&&(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom))help.current?.close();}}><header className="mp-help-heading"><h2>{t('mp_help')}</h2><button className="mp-help-close" aria-label={i18n.language==='zh'?'关闭提示':'Close help'} onClick={()=>help.current?.close()}>×</button></header><div className="mp-help-content"><p>{t('mp_help_text')}</p><p>Super Sudoku © 2023 Tom Nick · <a href="./LICENSE.upstream.txt" target="_blank" rel="noreferrer">MIT</a></p></div></dialog>{children}</>;
}
