import test from 'node:test';
import assert from 'node:assert/strict';
import '../src/phet/question-learning.js';

const {read,registerReader,algorithms,FAMILIES}=globalThis.MathPhysicsPhetQuestions;
const property=value=>({value});
function sim(id,model){const index=id==='balancing-act'?2:1,screens=Array.from({length:index+1},()=>({model:{}}));screens[index].model=model;return {simScreens:screens,screenIndexProperty:property(index),showHomeScreenProperty:property(false)};}
function frozen(o){if(o&&typeof o==='object'){for(const child of Object.values(o))frozen(child);Object.freeze(o);}return o;}
const fields=q=>{assert.ok(q.intent.length>10);for(const k of ['hints','steps','commonMistakes']){assert.ok(q[k].length>=({hints:3,steps:2,commonMistakes:2}[k]));assert.ok(q[k].every(s=>typeof s==='string'&&s.length>5&&!/undefined|NaN/.test(s)));}};

test('the pinned games enumerate 15 families and unknown families fail',()=>{assert.equal(FAMILIES.length,15);assert.equal(new Set(FAMILIES).size,15);const m={gameStateProperty:property('presentingInteractiveChallenge'),levelProperty:property(0),currentChallengeProperty:property({checkSpec:'unsupported'})};assert.throws(()=>read('area-builder',sim('area-builder',m)),/unknown area checkSpec/);});
test('home, chooser, non-game screens, unsupported simulations clear the current question',()=>{const s=sim('area-builder',{});s.showHomeScreenProperty.value=true;assert.equal(read('area-builder',s),null);s.showHomeScreenProperty.value=false;s.simScreens[1].model.gameStateProperty=property('choosingLevel');assert.equal(read('area-builder',s),null);s.screenIndexProperty.value=0;assert.equal(read('area-builder',s),null);assert.equal(read('states-of-matter-basics',s),null);});
test('old Joist current screen takes precedence over its homepage preselection',()=>{const s=sim('area-builder',{gameStateProperty:property('choosingLevel')}),home={};s.selectedScreenProperty=property(s.simScreens[1]);s.screenProperty=property(home);assert.equal(read('area-builder',s),null);s.screenProperty.value=s.simScreens[0];assert.equal(read('area-builder',s),null);});

for(const [kind,outer,holes,total]of [
 ['orthogonal',[[0,0],[3,0],[3,1],[1,1],[1,2],[0,2]],[],4],
 ['diagonal',[[0,0],[2,0],[0,2]],[],2],
 ['hole',[[0,0],[3,0],[3,3],[0,3]],[[[1,1],[2,1],[2,2],[1,2]]],8]
])test('entered area counts actual '+kind+' grids with immutable native data',()=>{const points=p=>p.map(([x,y])=>({x:x*35,y:y*35})),q=frozen({checkSpec:'areaEntered',backgroundShape:{unitLength:35,exteriorPerimeters:[points(outer)],interiorPerimeters:holes.map(points),unitArea:total}}),s=frozen(sim('area-builder',{gameStateProperty:property('presentingInteractiveChallenge'),levelProperty:property(2),currentChallengeProperty:property(q)}));const before=JSON.stringify(s),got=read('area-builder',s);fields(got);assert.equal(got.family,'areaEntered-'+kind);assert.equal(got.params.area,total);assert.equal(got.params.rows.reduce((n,r)=>n+r.whole+r.half/2,0),total);assert.equal(JSON.stringify(s),before);assert.equal(read('area-builder',s).fingerprint,got.fingerprint);});
test('unsupported partial cells and inconsistent native area fail explicitly',()=>{const q={checkSpec:'areaEntered',backgroundShape:{unitLength:1,exteriorPerimeters:[[{x:0,y:0},{x:1,y:0},{x:0,y:.5}]],interiorPerimeters:[],unitArea:.25}},s=sim('area-builder',{gameStateProperty:property('presentingInteractiveChallenge'),levelProperty:property(0),currentChallengeProperty:property(q)});assert.throws(()=>read('area-builder',s),/unsupported partial grid cell/);q.backgroundShape.exteriorPerimeters[0][2].y=1;q.backgroundShape.unitArea=1;assert.throws(()=>read('area-builder',s),/native area and counted grid disagree/);});
for(const checkSpec of ['areaConstructed','areaAndPerimeterConstructed','areaAndProportionConstructed','areaPerimeterAndProportionConstructed'])test(checkSpec+' checks the original solution cells and actual forest colors',()=>{const proportional=checkSpec.includes('Proportion'),perimeter=checkSpec.includes('Perimeter'),q=frozen({checkSpec,buildSpec:{area:4,...(perimeter?{perimeter:8}:{}),...(proportional?{proportions:{color1:'#70ad82',color2:'#315d4b',color1Proportion:{numerator:1,denominator:2}}}:{})},exampleBuildItSolution:[[0,0],[1,0],[0,1],[1,1]].map(([cellColumn,cellRow],i)=>({cellColumn,cellRow,color:i<2?'#70ad82':'#315d4b'}))}),s=frozen(sim('area-builder',{gameStateProperty:property('presentingInteractiveChallenge'),levelProperty:property(0),currentChallengeProperty:property(q)})),got=read('area-builder',s);fields(got);assert.equal(got.params.area,4);assert.ok(got.steps.join('').includes('= 4格'));if(proportional)assert.ok(got.steps.join('').includes('= 2格'));});

test('number-card solver shares a finite inventory across all targets',()=>{const targets=[{n:1,d:2},{n:2,d:3},{n:3,d:2}],pool=[{key:1,count:1},{key:2,count:3},{key:3,count:2}],before=JSON.stringify(pool),plan=algorithms.numberPlan(targets,pool),used=new Map();plan.forEach((p,i)=>{assert.equal(p.n*targets[i].d,p.d*targets[i].n);for(const v of [p.n,p.d])used.set(v,(used.get(v)||0)+1);});for(const p of pool)assert.ok((used.get(p.key)||0)<=p.count);assert.equal(JSON.stringify(pool),before);assert.throws(()=>algorithms.numberPlan([{n:1,d:1}],[{key:1,count:1}]),/no number construction/);});
test('number-card solver never puts zero in the denominator',()=>{assert.deepEqual(algorithms.numberPlan([{n:0,d:2}],[{key:0,count:2},{key:1,count:1}]),[{n:0,d:1}]);assert.throws(()=>algorithms.numberPlan([{n:0,d:2}],[{key:0,count:2}]),/no number construction/);});
test('shape solver uses only available unit fractions and each container is at most one',()=>{const targets=[{n:3,d:2},{n:2,d:3}],pool=[{key:2,count:3},{key:3,count:2}],before=JSON.stringify(pool),plan=algorithms.shapePlan(targets,pool,2);plan.forEach((p,i)=>{assert.ok(Math.abs(p.counts.reduce((n,c)=>n+c.count/c.d,0)-targets[i].n/targets[i].d)<1e-8);for(const container of p.containers)assert.ok(container.reduce((n,c)=>n+1/c.d,0)<=1+1e-8);});assert.equal(JSON.stringify(pool),before);assert.throws(()=>algorithms.shapePlan([{n:3,d:2}],[{key:2,count:3}],1),/no shape construction/);});
for(const shape of [true,false])test('build-fraction teaching follows targets and forbids unknown mixed construction '+shape,()=>{const q={hasShapes:shape,hasMixedTargets:false,challengeType:{name:shape?'PIE':'NUMBER'},maxTargetWholes:2,targets:[{fraction:{numerator:3,denominator:2},groupProperty:property(null)}],shapeStacks:[{fraction:{numerator:1,denominator:2},layoutQuantity:3}],numberStacks:[{number:3,layoutQuantity:1},{number:2,layoutQuantity:1}]},s=sim('fractions-intro',{levelProperty:property({number:10}),challengeProperty:property(q)}),got=read('fractions-intro',s);fields(got);assert.ok(got.intent.includes('3/2'));assert.ok(got.steps.join('').includes('3/2'));q.hasMixedTargets=true;assert.throws(()=>read('fractions-intro',s),/mixed-target construction/);});
for(const mixed of [false,true])test('matcher current selection updates without replacing native question identity '+mixed,()=>{const pieces=[{fraction:{numerator:3,denominator:2},hasMixedNumbers:mixed,spotProperty:property(null)},{fraction:{numerator:6,denominator:4},hasMixedNumbers:mixed,spotProperty:property(null)}],q={pieces,scaleSpots:[{pieceProperty:property(null)},{pieceProperty:property(null)}],isComplete:false},s=sim('fraction-matcher',{hasMixedNumbers:mixed,levelProperty:property({number:8}),challengeProperty:property(q)}),initial=read('fraction-matcher',s);fields(initial);q.scaleSpots[0].pieceProperty.value=pieces[0];q.scaleSpots[1].pieceProperty.value=pieces[1];const chosen=read('fraction-matcher',s);assert.equal(chosen.id,initial.id);assert.notEqual(chosen.fingerprint,initial.fingerprint);assert.ok(chosen.steps[0].includes('= 12'));q.pieces.pop();assert.throws(()=>read('fraction-matcher',s),/odd count/);});
test('matcher derives the reading process from every actual whole and shaded partition',()=>{const piece={fraction:{numerator:3,denominator:2},filledPartitions:[{shapePartition:{length:2},fills:[true,true]},{shapePartition:{length:2},fills:[false,true]}],spotProperty:property(null)},q=frozen({pieces:[piece,{fraction:{numerator:6,denominator:4},spotProperty:property(null)}],scaleSpots:[{pieceProperty:property(null)},{pieceProperty:property(null)}],isComplete:false}),s=frozen(sim('fraction-matcher',{hasMixedNumbers:false,levelProperty:property({number:3}),challengeProperty:property(q)})),before=JSON.stringify(s),got=read('fraction-matcher',s);fields(got);assert.deepEqual(got.params.cards[0].partitions,[{n:2,d:2},{n:1,d:2}]);assert.ok(got.steps.some(t=>t.includes('2/2 + 1/2 = 3/2')));assert.ok(got.hints[0].includes('分2份、涂2份'));assert.equal(JSON.stringify(s),before);});
test('unknown graphic fields and inconsistent actual shaded value fail explicitly',()=>{const piece={fraction:{numerator:1,denominator:2},filledPartitions:[{shapePartition:{length:2},fills:[true,true]}],spotProperty:property(null)},q={pieces:[piece,{fraction:{numerator:1,denominator:2},spotProperty:property(null)}],scaleSpots:[{pieceProperty:property(null)},{pieceProperty:property(null)}],isComplete:false},s=sim('fraction-matcher',{hasMixedNumbers:false,levelProperty:property({number:1}),challengeProperty:property(q)});assert.throws(()=>read('fraction-matcher',s),/visible graphic fills and native fraction disagree/);piece.filledPartitions[0].fills=[1,0];assert.throws(()=>read('fraction-matcher',s),/unknown graphic fills/);});
for(const type of ['position','mass','tilt'])test('balance '+type+' derives the current numeric relation from immutable masses',()=>{const fixedMassDistancePairs=type==='mass'?[{mass:{isMystery:true,massValue:20},distance:-1}]:[{mass:{massValue:10},distance:-1.5},...(type==='tilt'?[{mass:{massValue:5},distance:1}]:[])],q=frozen({viewConfig:{showMassEntryDialog:type==='mass',showTiltPredictionSelector:type==='tilt'},fixedMassDistancePairs,movableMasses:type==='position'?[{massValue:5}]:[],balancedConfiguration:type==='mass'?[{mass:{massValue:10},distance:2}]:type==='position'?[{mass:{massValue:5},distance:3}]:[]}),s=sim('balancing-act',{gameStateProperty:property('presentingInteractiveChallenge'),levelProperty:property(3),getCurrentChallenge:()=>q}),got=read('balancing-act',s);fields(got);assert.equal(got.params.answer,{position:3,mass:20,tilt:'左侧下降'}[type]);if(type==='mass'){assert.ok(!got.intent.includes('20千克'));assert.ok(got.steps.join('').includes('= 20千克'));}});
test('native teaching does not draw random numbers or invoke answer checks',()=>{const original=Math.random;Math.random=()=>{throw Error('RNG consumed');};try{const q=frozen({viewConfig:{},fixedMassDistancePairs:[{mass:{massValue:10},distance:-1}],movableMasses:[{massValue:5}],balancedConfiguration:[{mass:{massValue:5},distance:2}]}),s=frozen(sim('balancing-act',{gameStateProperty:property('presentingInteractiveChallenge'),levelProperty:property(0),getCurrentChallenge:()=>q,checkAnswer:()=>{throw Error('native scoring invoked');}}));fields(read('balancing-act',s));}finally{Math.random=original;}});
test('registered readonly readers share strict family/field validation',()=>{registerReader('fixture',()=>({id:'fixture/1',contextId:'fixture/game',simId:'fixture',familyId:'fixture/test',fingerprint:'1',intent:'当前真实目标',hints:['a','b','c'],steps:['a','b'],commonMistakes:['a','b']}),{families:['fixture/test']});assert.equal(read('fixture',{}).id,'fixture/1');assert.throws(()=>registerReader('fixture',()=>null,{families:['fixture/other']}),/duplicate reader/);registerReader('bad-fixture',()=>({simId:'bad-fixture',familyId:'bad-fixture/unknown'}),{families:['bad-fixture/known']});assert.throws(()=>read('bad-fixture',{}),/unknown registered family/);});
test('watch publishes only changed snapshots, clears home, and releases its timer',()=>{const oldSet=globalThis.setInterval,oldClear=globalThis.clearInterval;let tick,cleared=false,current={id:'watch-fixture/current',contextId:'watch-fixture/game',simId:'watch-fixture',familyId:'watch-fixture/test',fingerprint:'initial',intent:'读取当前题目',hints:['a','b','c'],steps:['a','b'],commonMistakes:['a','b']};registerReader('watch-fixture',()=>current,{families:['watch-fixture/test']});globalThis.setInterval=fn=>{tick=fn;return 42;};globalThis.clearInterval=id=>{assert.equal(id,42);cleared=true;};try{const updates=[],s={showHomeScreenProperty:property(false)},watch=globalThis.MathPhysicsPhetQuestions.watch('watch-fixture',s,q=>updates.push(q));assert.equal(updates.length,1);tick();assert.equal(updates.length,1);current={...current,fingerprint:'changed'};tick();assert.equal(updates.length,2);assert.equal(updates[1].id,updates[0].id);s.showHomeScreenProperty.value=true;tick();assert.equal(updates.at(-1),null);assert.equal(watch.snapshot(),null);watch.dispose();assert.ok(cleared);}finally{globalThis.setInterval=oldSet;globalThis.clearInterval=oldClear;}});
