import {TOPICS,generateWorksheet,exportRecipe,exportWorksheet,importRecipe,answerText,listPracticeTemplates} from './engine.mjs';
import {emptyAttempt,checkAttempt,stats,saveSession,loadSession,recordCompletion,sessionSnapshot} from './session.mjs';
import {getUnit} from '../primary-math/curriculum.mjs';
export function mountPractice(root,{context=null,grade=1,difficulty=1,onRestore=()=>{},onProgress=()=>{},onSolve=()=>{}}={}){
 const $=id=>root.querySelector(`#practice-${id}`),element=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const storage=window.MathPhysicsSync?.createStorage()||{getItem:key=>window.localStorage.getItem(key),setItem:(key,value)=>window.localStorage.setItem(key,value)};
 let sheet,attempts={},selection=context,currentGrade=grade,completedLevels={},seed='数与生活',popups=[];
 function status(text='',error=false){$('status').textContent=text;$('status').className=error?'error':'';}
 function persist(){if(!saveSession(storage,sheet,attempts,completedLevels))status('练习记录未能保存，可下载练习设置。',true);}
 function score(){const s=stats(sheet,attempts);completedLevels=recordCompletion(sheet,attempts,completedLevels);onProgress(completedLevels);$('score').replaceChildren(...[[s.solved,'已答对'],[s.total,'题目']].map(([n,label])=>{const e=element('span');e.append(element('strong',n),document.createTextNode(label));return e;}));}
 function diagram(q){if(!q.visual)return null;const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 300 175');svg.setAttribute('class','diagram');svg.setAttribute('role','img');svg.setAttribute('aria-label',q.visual.label||'图形尺寸示意图');if(q.visual.type==='svg'){svg.innerHTML=q.visual.svg;return svg;}const add=(tag,attrs,text)=>{const node=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))node.setAttribute(k,String(v));if(text)node.textContent=text;svg.append(node);};if(q.visual.type==='triangle'){add('polygon',{points:'45,125 255,125 115,25',fill:'var(--mp-leaf)',stroke:'var(--mp-primary)'});add('line',{x1:115,y1:25,x2:115,y2:125,stroke:'var(--mp-orange)','stroke-dasharray':'5 4'});}else add('rect',{x:45,y:25,width:210,height:100,fill:'var(--mp-leaf)',stroke:'var(--mp-primary)'});add('text',{x:125,y:150},`${q.visual.width}厘米`);add('text',{x:5,y:80},`${q.visual.height}厘米`);return svg;}
 function card(q,index){
  const article=element('article',undefined,'question');article.dataset.questionId=q.id;const head=element('header'),trigger=element('button','提示','mp-help-trigger');trigger.type='button';head.append(element('b',`第${index+1}题`),trigger);article.append(head,element('h3',q.prompt));const svg=diagram(q);if(svg)article.append(svg);
  const form=element('form'),label=element('label','你的答案'),row=element('div',undefined,'answer-row'),input=element(q.answer.type==='choice'?'select':'input'),check=element('button','检查答案','primary');input.id=`practice-answer-${index}`;label.htmlFor=input.id;input.name='answer';if(q.answer.type==='choice')input.append(new Option('请选择',''),...q.answer.choices.map(x=>new Option(x,x)));else{input.type='text';input.maxLength=80;input.autocomplete='off';input.spellcheck=false;input.placeholder=q.answer.requirePercent?'例如25%':'整数、小数或分数';}check.type='submit';row.append(input,element('span',q.answer.unit||'','unit'),check);form.append(label,row);const feedback=element('div',undefined,'feedback');feedback.setAttribute('role','status');article.append(form,feedback);
  const content=element('section'),hint=element('button','下一步提示'),solution=element('button','查看解题过程'),hints=element('ol'),answer=element('div');hint.type=solution.type='button';content.append(element('p',q.intent),hint,hints,solution,answer);const popup=window.MathPhysicsHelp.create({title:`第${index+1}题 · 提示`,content,trigger,parent:article});popups.push(popup);
  function paint(){const a=attempts[q.id]||emptyAttempt();input.value=a.input;input.disabled=check.disabled=a.solved;feedback.textContent=a.message;feedback.className=`feedback${a.solved?' correct':''}`;hint.disabled=a.hints>=q.hints.length;hint.textContent=`下一步提示 ${a.hints}/${q.hints.length}`;hints.replaceChildren(...q.hints.slice(0,a.hints).map(text=>element('li',text)));answer.replaceChildren();solution.disabled=a.revealed;if(a.revealed){const steps=element('ol'),mistakes=element('ul');steps.append(...q.steps.map(t=>element('li',t)));mistakes.append(...q.commonMistakes.map(t=>element('li',t)));answer.append(element('h4','解题过程'),element('p',`参考答案：${answerText(q.answer)}${q.answer.unit||''}`),steps,element('h4','常见错误'),mistakes);}}
  form.onsubmit=e=>{e.preventDefault();const update=checkAttempt(q,attempts[q.id],input.value);if(update.result.valid){attempts[q.id]=update.attempt;paint();score();persist();if(update.result.correct)onSolve(q);}else{feedback.textContent=update.result.message;input.focus();}};
  hint.onclick=()=>{const a=attempts[q.id]||emptyAttempt();attempts[q.id]={...a,input:input.value,hints:Math.min(q.hints.length,a.hints+1)};paint();persist();};solution.onclick=()=>{const a=attempts[q.id]||emptyAttempt();attempts[q.id]={...a,input:input.value,revealed:true};paint();score();persist();};paint();return article;
 }
 function render(){for(const popup of popups)popup.destroy();popups=[];$('questions').replaceChildren(...sheet.questions.map(card));score();}
 function available(){return listPracticeTemplates({curriculum:selection,grade:currentGrade,difficulty:Number($('difficulty').value),topic:$('topic').value});}
 function limit(){
  const selected=$('template').value,ids=selected==='all'?available().map(t=>t.id):[selected],level=Number($('difficulty').value),finite=level===1?{'sg.shape2d':6,'sg.measure-unit':4,'sg.shape3d':4,'sg.lines':2,'sg.nets':4}:{'sg.lines':1};
  if(currentGrade===3&&level>1)finite['geometry.angle-kind']=level===2?3:2;
  const capacity=id=>id.startsWith('fixed.')?1:finite[id],count=ids.every(id=>capacity(id))?ids.reduce((sum,id)=>sum+capacity(id),0):500;
  $('count').max=count;$('count').value=Math.min(Number($('count').value)||8,count);
 }
 function refresh(){const previous=$('template').value,keepImported=previous==='__imported'&&sheet?.templateIds.length>1&&JSON.stringify(selection)===JSON.stringify(sheet.curriculum||null)&&currentGrade===(sheet.grade||sheet.curriculum?.grade||currentGrade)&&Number($('difficulty').value)===sheet.difficulty;$('template').replaceChildren(new Option('混合练习','all'),...available().map(t=>new Option(t.title,t.id)));if(keepImported)$('template').append(new Option('已保存的题型组合','__imported'));if([...$('template').options].some(o=>o.value===previous))$('template').value=previous;limit();}
 function fill(){seed=sheet.seed;selection=sheet.curriculum||null;currentGrade=sheet.grade||selection?.grade||currentGrade;$('difficulty').value=sheet.difficulty;$('count').value=sheet.count;$('topic').value='all';refresh();if(sheet.templateIds.length===1&&[...$('template').options].some(o=>o.value===sheet.templateIds[0]))$('template').value=sheet.templateIds[0];else if(sheet.templateIds.length>1){$('template').append(new Option('已保存的题型组合','__imported'));$('template').value='__imported';}}
 function generate(){try{const template=$('template').value,topic=$('topic').value;const next=generateWorksheet({seed,count:Number($('count').value),difficulty:Number($('difficulty').value),practiceVersion:template==='__imported'?sheet.practiceVersion:2,grade:currentGrade,...(selection?{curriculum:selection}:{}),...(template==='__imported'?{templateIds:sheet.templateIds}:template!=='all'?{templateIds:[template]}:{}),...(!selection&&topic!=='all'?{topics:[topic]}:{})});sheet=next;attempts={};render();status();persist();}catch(e){status(e.message,true);}}
 function newPractice(){const values=new Uint32Array(2);crypto.getRandomValues(values);seed=values.join('-');generate();}
 function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'})),a=element('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
 for(const [id,title]of Object.entries(TOPICS))$('topic').append(new Option(title,id));$('difficulty').value=difficulty;refresh();$('topic-field').hidden=!!selection;
 $('settings').onsubmit=e=>{e.preventDefault();generate();};$('new-seed').onclick=newPractice;$('template').onchange=()=>{limit();newPractice();};$('topic').onchange=()=>{refresh();newPractice();};
 $('export-student').onclick=()=>download(exportWorksheet(sheet),'数学练习.json');$('export-teacher').onclick=()=>download(exportWorksheet(sheet,{includeAnswers:true}),'数学练习与解析.json');$('export-recipe').onclick=()=>download(exportRecipe(sheet),'练习设置.json');$('print').onclick=()=>window.print();
 $('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('文件不能超过2MB');sheet=importRecipe(await file.text());attempts={};fill();onRestore(selection,sheet.difficulty,currentGrade);render();persist();status();}catch(error){status(`恢复失败：${error.message}`,true);}finally{e.target.value='';}};
 const remote=window.MathPhysicsSync?.getSnapshot('question-bank');
 const saved=remote?loadSession({getItem:()=>JSON.stringify(remote)}):loadSession(storage);if(saved.status==='restored'){sheet=saved.sheet;attempts=saved.attempts;completedLevels=saved.completedLevels;fill();onRestore(selection,sheet.difficulty,currentGrade);render();}else{generate();if(saved.status==='unavailable')status('上次记录无法恢复，已打开新练习。',true);}
 window.MathPhysicsSync?.register('question-bank',()=>sessionSnapshot(sheet,attempts,completedLevels),window);
 return {setContext(value,level,{generateNew=false,grade=currentGrade}={}){selection=value;currentGrade=grade;$('difficulty').value=level;$('topic-field').hidden=!!selection;$('topic').value='all';refresh();if(generateNew)newPractice();},snapshot(){return {sheet,attempts,completedLevels};}};
}
