/** 题型注册表。reference 表示知识点参考，不表示导入了上游代码或完整题库。 */
export const TOPICS = Object.freeze({arithmetic:'整数与运算',numbers:'数感与规律',fractions:'分数',decimals:'小数',percent:'百分数与比例',measurement:'测量与时间',geometry:'面积与体积',data:'统计与可能性',word:'生活应用'});
const rows = [
 ['integer.add','arithmetic','整数加法','mm-basic'],
 ['integer.subtract','arithmetic','整数减法','mm-basic'],
 ['integer.multiply','arithmetic','乘法练习','mm-tables'],
 ['integer.divide','arithmetic','整除练习','mm-tables'],
 ['integer.missing','arithmetic','寻找未知加数','mm-basic'],
 ['integer.mixed','arithmetic','先乘除后加减','mm-basic'],
 ['integer.parentheses','arithmetic','带括号的运算','mm-basic'],
 ['integer.remainder','arithmetic','求除法的余数','mm-basic'],
 ['number.place','numbers','认识数位','mm-basic'],
 ['number.round','numbers','四舍五入','mm-basic'],
 ['number.compare','numbers','比较整数大小','mm-basic'],
 ['number.sequence','numbers','等差数列找规律','mm-basic'],
 ['number.double','numbers','求一个数的两倍','mm-basic'],
 ['number.half','numbers','求一个数的一半','mm-basic'],
 ['fraction.simplify','fractions','分数约分','mm-fractions'],
 ['fraction.equivalent','fractions','补全等值分数','mm-fractions'],
 ['fraction.compare','fractions','分数比较','mm-fractions'],
 ['fraction.add-like','fractions','同分母分数加法','mm-fractions'],
 ['fraction.add','fractions','异分母分数加法','mm-fractions'],
 ['fraction.subtract','fractions','分数减法','mm-fractions'],
 ['fraction.multiply','fractions','分数乘法','ma-extension'],
 ['fraction.divide','fractions','分数除法','ma-extension'],
 ['fraction.quantity','fractions','求一个数量的几分之几','mm-fractions'],
 ['decimal.add','decimals','小数加法','mm-basic'],
 ['decimal.subtract','decimals','小数减法','mm-basic'],
 ['decimal.multiply','decimals','小数乘法','mm-basic'],
 ['decimal.divide','decimals','小数除以整数','mm-basic'],
 ['decimal.scale','decimals','小数乘以十的整次幂','mm-basic'],
 ['percent.convert','percent','小数化百分数','mm-basic'],
 ['percent.quantity','percent','求一个数量的百分之几','mm-basic'],
 ['percent.discount','percent','折扣与现价','ma-extension'],
 ['measure.length','measurement','长度单位换算','mm-basic'],
 ['measure.mass','measurement','质量单位换算','mm-basic'],
 ['measure.area','measurement','面积单位换算','mm-area'],
 ['measure.duration','measurement','时与分的换算','mm-basic'],
 ['measure.elapsed','measurement','计算经过时间','mm-basic'],
 ['geometry.perimeter','geometry','长方形周长','mm-area'],
 ['geometry.rectangle','geometry','长方形面积','mm-area'],
 ['geometry.triangle','geometry','三角形面积','ma-extension'],
 ['geometry.volume','geometry','长方体体积','ma-extension'],
 ['geometry.angle','geometry','三角形内角和','ma-extension'],
 ['data.mean','data','求平均数','ma-extension'],
 ['data.range','data','最大值与最小值之差','ma-extension'],
 ['data.probability','data','摸球的可能性','ma-extension'],
 ['word.shopping','word','购物总价','mm-money'],
 ['word.change','word','购物找零','mm-money'],
 ['word.groups','word','平均分配','mm-basic'],
 ['word.speed','word','路程、速度和时间','ma-extension']
];
export const SOURCES = Object.freeze({
 'mm-basic': {project:'MathsMentales',mode:'concept-reference',url:'https://mathsmentales.net/liste-des-exercices.html',note:'参考基础技能分类；生成参数、中文题干、提示与实现由本项目独立编写。'},
 'mm-tables': {project:'MathsMentales',mode:'concept-reference',referenceId:'6ND6',url:'https://mathsmentales.net/index.html?u=6ND6',note:'乘法表知识点参考，非原题翻译或源码移植。'},
 'mm-fractions': {project:'MathsMentales',mode:'concept-reference',referenceIds:['6NB5','5NC7'],url:'https://mathsmentales.net/index.html?u=6NB5',note:'分数约分与加法活动参考，其他分数题为独立补充。'},
 'mm-money': {project:'MathsMentales',mode:'concept-reference',referenceId:'6NF1',url:'https://mathsmentales.net/index.html?u=6NF1',note:'找零知识点参考；使用人民币元、角、分关系。'},
 'mm-area': {project:'MathsMentales',mode:'concept-reference',referenceId:'6MC1',url:'https://mathsmentales.net/index.html?u=6MC1',note:'常见面积主题参考，单位换算为本项目独立补充。'},
 'ma-extension': {project:'MathALÉA',mode:'topic-reference-only',url:'https://forge.apps.education.fr/coopmaths/mathalea',note:'进阶主题组织参考；未复制 AGPL 源码、原题文字、图片或校验器。'}
});
export const TEMPLATES = Object.freeze(rows.map(([id,topic,title,reference])=>Object.freeze({id,topic,title,reference,difficulties:[1,2,3],locale:'zh-CN',implementation:'original',license:'MIT'})));
