import React from 'react';
import Button from '../Button';
import {CellCoordinates} from 'src/lib/engine/types';
import {useTranslation} from 'react-i18next';

const Icon=({name}:{name:string})=><img className="sudoku-action-icon" src={`./icons/${name}.svg`} width="24" height="24" alt=""/>;
export const UndoButton=({canUndo,undo}:{canUndo:boolean;undo:()=>void})=>{const {t}=useTranslation();return <Button data-testid="sudoku-undo" disabled={!canUndo} onClick={undo}><Icon name="undo"/>{t('undo_btn')}</Button>;};
export const RedoButton=({canRedo,redo}:{canRedo:boolean;redo:()=>void})=>{const {t}=useTranslation();return <Button data-testid="sudoku-redo" disabled={!canRedo} onClick={redo}><Icon name="redo"/>{t('mp_redo')}</Button>;};
export const EraseButton=({activeCellCoordinates,clearCell,disabled=false}:{activeCellCoordinates?:CellCoordinates;clearCell:(cell:CellCoordinates)=>void;disabled?:boolean})=>{const {t}=useTranslation();return <Button data-testid="sudoku-erase" disabled={disabled||!activeCellCoordinates} onClick={()=>activeCellCoordinates&&clearCell(activeCellCoordinates)}><Icon name="erase"/>{t('erase_btn')}</Button>;};
export function ModePicker({notesMode,activateNotesMode,deactivateNotesMode}:{notesMode:boolean;activateNotesMode:()=>void;deactivateNotesMode:()=>void}){const {t}=useTranslation();return <div className="sudoku-mode-picker" role="group" aria-label={t('mp_mode')}><button type="button" data-testid="sudoku-mode-fill" aria-pressed={!notesMode} onClick={deactivateNotesMode}>{t('mp_fill')}</button><button type="button" data-testid="sudoku-mode-notes" aria-pressed={notesMode} onClick={activateNotesMode}><Icon name="pencil"/>{t('mp_notes')}</button></div>;}
type Props={notesMode:boolean;activeCellCoordinates?:CellCoordinates;clearCell:(cell:CellCoordinates)=>void;activateNotesMode:()=>void;deactivateNotesMode:()=>void;getHint:(cell:CellCoordinates)=>void;canUndo:boolean;undo:()=>void;canRedo:boolean;redo:()=>void;disabled?:boolean;locked?:boolean};
export default function SudokuMenuControls({activeCellCoordinates,clearCell,getHint,canUndo,undo,canRedo,redo,disabled=false,locked=false}:Props){const {t}=useTranslation();return <div className="sudoku-action-row"><EraseButton activeCellCoordinates={activeCellCoordinates} clearCell={clearCell} disabled={disabled||locked}/><UndoButton canUndo={canUndo&&!disabled} undo={undo}/><RedoButton canRedo={canRedo&&!disabled} redo={redo}/><Button data-testid="sudoku-hint" disabled={disabled||locked||!activeCellCoordinates} onClick={()=>activeCellCoordinates&&getHint(activeCellCoordinates)}><Icon name="hint"/>{t('hint_btn')}</Button></div>;}
