// Extract the complete pinned Rush collection and verify exact shortest paths.
// Never writes into vendor; generated data is consumed offline by the lesson.
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { parseBoard, parseWalls, solveLevel } from '../lessons/spatial-games/games/rush-model.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'vendor/games/spatial/rush');
const target = path.join(root, 'lessons/spatial-games/games/generated-rush-data.js');
const forty = await fs.readFile(path.join(source, 'cmd/forty/main.go'), 'utf8');
const web = await fs.readFile(path.join(source, 'web/app.js'), 'utf8');
const rowMatches = [...forty.matchAll(/"([A-Z.]{6})"/g)];
if (rowMatches.length !== 240) throw new Error('Expected all 40 upstream six-row boards');
const definitions = [];
for (let i = 0; i < rowMatches.length; i += 6) {
  const sourceNumber = i / 6 + 1;
  definitions.push({ sourceId: `forty-${String(sourceNumber).padStart(2, '0')}`, sourceNumber, sourceFile: 'cmd/forty/main.go', sourceLine: forty.slice(0, rowMatches[i].index).split('\n').length, rows: rowMatches.slice(i, i + 6).map(match => match[1]) });
}
const defaults = [...web.matchAll(/new Board\("([A-Z.ox]{36})"\)/g)];
const distinctDefaults = [...new Set(defaults.map(match => match[1]))];
if (distinctDefaults.length !== 1) throw new Error('Expected one distinct original web default');
const defaultMatch = defaults[0];
definitions.push({ sourceId: 'web-default', sourceNumber: null, sourceFile: 'web/app.js', sourceLine: web.slice(0, defaultMatch.index).split('\n').length, rows: distinctDefaults[0].match(/.{6}/g) });
if (new Set(definitions.map(level => level.rows.join('').replaceAll('o', '.'))).size !== 41) throw new Error('Source boards must be distinct');
for (const level of definitions) {
  const model = { id: level.sourceId, vehicles: parseBoard(level.rows), walls: parseWalls(level.rows) };
  const solution = solveLevel(model);
  if (!solution) throw new Error(`Unsolved source board: ${level.sourceId}`);
  level.minimumMoves = solution.length;
  level.solution = solution;
}
const hashes = Object.fromEntries([['cmd/forty/main.go', forty], ['web/app.js', web]].map(([name, text]) => [name, createHash('sha256').update(text).digest('hex')]));
const output = `// Generated by scripts/build_spatial_rush.mjs from preserved MIT source.\n// A step is one uninterrupted slide; the final slide takes red A out of the board.\nexport const sourceHashes = ${JSON.stringify(hashes, null, 2)};\nexport const sourceLevels = ${JSON.stringify(definitions, null, 2)};\n`;
if (process.argv.includes('--check')) {
  if (await fs.readFile(target, 'utf8') !== output) throw new Error('Rush generated levels are stale; run node scripts/build_spatial_rush.mjs');
  console.log(`Verified ${definitions.length} original Rush layouts and shortest solutions.`);
} else {
  await fs.writeFile(target, output);
  console.log(`Generated ${definitions.length} original Rush layouts: ${definitions.map(level => `${level.sourceId}=${level.minimumMoves}`).join(', ')}`);
}
